markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title
paginate: 5
paginate_path: page/:num

blog:
    name:                                                # 博客名称
    description: 杂谈, Algorithm, ML， NLP， PGM                                         # 博客描述
    title: zzhaozeng's blog                                               # 网页标题
    url:                                                 # 博客地址
    duoshuo: zazazeng                                             # 多说ID
    tongji: zazazeng                                              # 百度统计ID
    qiniu:                                               # 七牛云地址
author:
    name: zzhaozeng                                                # 作者名称
    email: zzhao.zeng@gmail.com                                              # 邮箱地址
    weibo: http://weibo.com/zazazeng/                                               # 微博地址
    github: zzhaozeng@github.com                                             # GitHub地址
    logo: /res/img/logo.jpg                                                # logo地址
    douban:
        name:                                            # 豆瓣地址名称
        key:                                             # 豆瓣API Key
